spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/jpmsql?serverTimezone=UTC
    username: jpmuser
    password: jpmtest123
#spring.datasource.url=jdbc:mysql://remotemysql.com:3306/f7KvEa34iU?serverTimezone=UTC
#spring.datasource.username=f7KvEa34iU
#spring.datasource.password=8ZDdHOqZLR
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${random.value}:${spring.application.name}
